/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface ForeignCrosschainGranterInterface extends utils.Interface {
  functions: {
    "foreignGateway()": FunctionFragment;
    "owner()": FunctionFragment;
    "proposalIdToVault(bytes32)": FunctionFragment;
    "registerVaultFromProposalOnTokenHomeChain(bytes32,address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setGateway(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "upgradePermissionVaultFromProposal(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "foreignGateway"
      | "owner"
      | "proposalIdToVault"
      | "registerVaultFromProposalOnTokenHomeChain"
      | "renounceOwnership"
      | "setGateway"
      | "transferOwnership"
      | "upgradePermissionVaultFromProposal"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "foreignGateway",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalIdToVault",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerVaultFromProposalOnTokenHomeChain",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setGateway", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradePermissionVaultFromProposal",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "foreignGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalIdToVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerVaultFromProposalOnTokenHomeChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradePermissionVaultFromProposal",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "VaultFromProposalPermissionUpgradeRequested(bytes32,address)": EventFragment;
    "VaultFromProposalRegisteredOnForeignChain(bytes32,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "VaultFromProposalPermissionUpgradeRequested"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "VaultFromProposalRegisteredOnForeignChain"
  ): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface VaultFromProposalPermissionUpgradeRequestedEventObject {
  proposalId: string;
  user: string;
}
export type VaultFromProposalPermissionUpgradeRequestedEvent = TypedEvent<
  [string, string],
  VaultFromProposalPermissionUpgradeRequestedEventObject
>;

export type VaultFromProposalPermissionUpgradeRequestedEventFilter =
  TypedEventFilter<VaultFromProposalPermissionUpgradeRequestedEvent>;

export interface VaultFromProposalRegisteredOnForeignChainEventObject {
  proposalId: string;
  tokenContract: string;
}
export type VaultFromProposalRegisteredOnForeignChainEvent = TypedEvent<
  [string, string],
  VaultFromProposalRegisteredOnForeignChainEventObject
>;

export type VaultFromProposalRegisteredOnForeignChainEventFilter =
  TypedEventFilter<VaultFromProposalRegisteredOnForeignChainEvent>;

export interface ForeignCrosschainGranter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ForeignCrosschainGranterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    foreignGateway(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proposalIdToVault(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { proposalId: string; tokenContract: string }
    >;

    registerVaultFromProposalOnTokenHomeChain(
      proposalId: BytesLike,
      tokenContract: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setGateway(
      _foreignGateway: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    upgradePermissionVaultFromProposal(
      proposalId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  foreignGateway(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  proposalIdToVault(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<[string, string] & { proposalId: string; tokenContract: string }>;

  registerVaultFromProposalOnTokenHomeChain(
    proposalId: BytesLike,
    tokenContract: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setGateway(
    _foreignGateway: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  upgradePermissionVaultFromProposal(
    proposalId: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    foreignGateway(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    proposalIdToVault(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string] & { proposalId: string; tokenContract: string }
    >;

    registerVaultFromProposalOnTokenHomeChain(
      proposalId: BytesLike,
      tokenContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setGateway(
      _foreignGateway: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradePermissionVaultFromProposal(
      proposalId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "VaultFromProposalPermissionUpgradeRequested(bytes32,address)"(
      proposalId?: BytesLike | null,
      user?: string | null
    ): VaultFromProposalPermissionUpgradeRequestedEventFilter;
    VaultFromProposalPermissionUpgradeRequested(
      proposalId?: BytesLike | null,
      user?: string | null
    ): VaultFromProposalPermissionUpgradeRequestedEventFilter;

    "VaultFromProposalRegisteredOnForeignChain(bytes32,address)"(
      proposalId?: BytesLike | null,
      tokenContract?: string | null
    ): VaultFromProposalRegisteredOnForeignChainEventFilter;
    VaultFromProposalRegisteredOnForeignChain(
      proposalId?: BytesLike | null,
      tokenContract?: string | null
    ): VaultFromProposalRegisteredOnForeignChainEventFilter;
  };

  estimateGas: {
    foreignGateway(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proposalIdToVault(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerVaultFromProposalOnTokenHomeChain(
      proposalId: BytesLike,
      tokenContract: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setGateway(
      _foreignGateway: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    upgradePermissionVaultFromProposal(
      proposalId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    foreignGateway(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposalIdToVault(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerVaultFromProposalOnTokenHomeChain(
      proposalId: BytesLike,
      tokenContract: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setGateway(
      _foreignGateway: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    upgradePermissionVaultFromProposal(
      proposalId: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
