/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface VaultInterface extends utils.Interface {
  functions: {
    "DOMAIN_SEPARATOR()": FunctionFragment;
    "PERMISSION_NONE()": FunctionFragment;
    "PERMISSION_READ()": FunctionFragment;
    "PERMISSION_WRITE()": FunctionFragment;
    "balanceOf(address,uint256)": FunctionFragment;
    "balanceOfBatch(address[],uint256[])": FunctionFragment;
    "createVault(uint256,string,string)": FunctionFragment;
    "eip712Domain()": FunctionFragment;
    "getCurrentSchema()": FunctionFragment;
    "getNonce(address)": FunctionFragment;
    "getPermission(uint256,address)": FunctionFragment;
    "getSchema(uint256)": FunctionFragment;
    "getVaultOwner(uint256)": FunctionFragment;
    "getVaultSchemaIndex(uint256)": FunctionFragment;
    "grantAccess(address,uint256,uint8)": FunctionFragment;
    "grantAccessWithSignature(address,uint256,uint8,uint256,bytes)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "lastSchemaIndex()": FunctionFragment;
    "nonces(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "permissions(uint256,address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "revokeAccess(uint256,address)": FunctionFragment;
    "safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "safeTransferFrom(address,address,uint256,uint256,bytes)": FunctionFragment;
    "schemaCIDs(uint256)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "setSchema(string)": FunctionFragment;
    "setURI(string)": FunctionFragment;
    "storeContentBatch(uint256,bytes[],bool,bytes[])": FunctionFragment;
    "storeContentBatchWithSignature(uint256,bytes[],bool,bytes[],uint256,bytes)": FunctionFragment;
    "storeContentWithMetadata(uint256,bytes,bool,bytes)": FunctionFragment;
    "storeContentWithMetadataSigned(uint256,bytes,bool,bytes,uint256,bytes)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferVaultOwnership(uint256,address)": FunctionFragment;
    "upgradePermission(uint256,address,uint8)": FunctionFragment;
    "uri(uint256)": FunctionFragment;
    "vaultExists(uint256)": FunctionFragment;
    "vaults(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DOMAIN_SEPARATOR"
      | "PERMISSION_NONE"
      | "PERMISSION_READ"
      | "PERMISSION_WRITE"
      | "balanceOf"
      | "balanceOfBatch"
      | "createVault"
      | "eip712Domain"
      | "getCurrentSchema"
      | "getNonce"
      | "getPermission"
      | "getSchema"
      | "getVaultOwner"
      | "getVaultSchemaIndex"
      | "grantAccess"
      | "grantAccessWithSignature"
      | "isApprovedForAll"
      | "lastSchemaIndex"
      | "nonces"
      | "owner"
      | "permissions"
      | "renounceOwnership"
      | "revokeAccess"
      | "safeBatchTransferFrom"
      | "safeTransferFrom"
      | "schemaCIDs"
      | "setApprovalForAll"
      | "setSchema"
      | "setURI"
      | "storeContentBatch"
      | "storeContentBatchWithSignature"
      | "storeContentWithMetadata"
      | "storeContentWithMetadataSigned"
      | "supportsInterface"
      | "transferOwnership"
      | "transferVaultOwnership"
      | "upgradePermission"
      | "uri"
      | "vaultExists"
      | "vaults"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERMISSION_NONE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERMISSION_READ",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERMISSION_WRITE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentSchema",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getNonce", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getPermission",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSchema",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultSchemaIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccessWithSignature",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "lastSchemaIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "permissions",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "safeBatchTransferFrom",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "schemaCIDs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setSchema", values: [string]): string;
  encodeFunctionData(functionFragment: "setURI", values: [string]): string;
  encodeFunctionData(
    functionFragment: "storeContentBatch",
    values: [BigNumberish, BytesLike[], boolean, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "storeContentBatchWithSignature",
    values: [
      BigNumberish,
      BytesLike[],
      boolean,
      BytesLike[],
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "storeContentWithMetadata",
    values: [BigNumberish, BytesLike, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeContentWithMetadataSigned",
    values: [
      BigNumberish,
      BytesLike,
      boolean,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferVaultOwnership",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradePermission",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "uri", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "vaultExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vaults",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERMISSION_NONE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERMISSION_READ",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERMISSION_WRITE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentSchema",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSchema", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultSchemaIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccessWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastSchemaIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "permissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeBatchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "schemaCIDs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSchema", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storeContentBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeContentBatchWithSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeContentWithMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeContentWithMetadataSigned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferVaultOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradePermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;

  events: {
    "ApprovalForAll(address,address,bool)": EventFragment;
    "ContentStoredWithMetadata(address,uint256,bytes,bool,bytes,bool)": EventFragment;
    "EIP712DomainChanged()": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PermissionUpgraded(address,uint256,uint8)": EventFragment;
    "SchemaSet(uint256,string)": EventFragment;
    "TransferBatch(address,address,address,uint256[],uint256[])": EventFragment;
    "TransferSingle(address,address,address,uint256,uint256)": EventFragment;
    "URI(string,uint256)": EventFragment;
    "VaultAccessGranted(address,uint256,uint8)": EventFragment;
    "VaultAccessRevoked(address,uint256)": EventFragment;
    "VaultCreated(uint256,address,string,string,string)": EventFragment;
    "VaultTransferred(uint256,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContentStoredWithMetadata"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PermissionUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SchemaSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferBatch"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferSingle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "URI"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultAccessGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultAccessRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultTransferred"): EventFragment;
}

export interface ApprovalForAllEventObject {
  account: string;
  operator: string;
  approved: boolean;
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export interface ContentStoredWithMetadataEventObject {
  sender: string;
  tokenId: BigNumber;
  encryptedCID: string;
  isCIDEncrypted: boolean;
  metadata: string;
  isMetadataSigned: boolean;
}
export type ContentStoredWithMetadataEvent = TypedEvent<
  [string, BigNumber, string, boolean, string, boolean],
  ContentStoredWithMetadataEventObject
>;

export type ContentStoredWithMetadataEventFilter =
  TypedEventFilter<ContentStoredWithMetadataEvent>;

export interface EIP712DomainChangedEventObject {}
export type EIP712DomainChangedEvent = TypedEvent<
  [],
  EIP712DomainChangedEventObject
>;

export type EIP712DomainChangedEventFilter =
  TypedEventFilter<EIP712DomainChangedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PermissionUpgradedEventObject {
  user: string;
  tokenId: BigNumber;
  newPermission: number;
}
export type PermissionUpgradedEvent = TypedEvent<
  [string, BigNumber, number],
  PermissionUpgradedEventObject
>;

export type PermissionUpgradedEventFilter =
  TypedEventFilter<PermissionUpgradedEvent>;

export interface SchemaSetEventObject {
  index: BigNumber;
  schemaCID: string;
}
export type SchemaSetEvent = TypedEvent<
  [BigNumber, string],
  SchemaSetEventObject
>;

export type SchemaSetEventFilter = TypedEventFilter<SchemaSetEvent>;

export interface TransferBatchEventObject {
  operator: string;
  from: string;
  to: string;
  ids: BigNumber[];
  values: BigNumber[];
}
export type TransferBatchEvent = TypedEvent<
  [string, string, string, BigNumber[], BigNumber[]],
  TransferBatchEventObject
>;

export type TransferBatchEventFilter = TypedEventFilter<TransferBatchEvent>;

export interface TransferSingleEventObject {
  operator: string;
  from: string;
  to: string;
  id: BigNumber;
  value: BigNumber;
}
export type TransferSingleEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  TransferSingleEventObject
>;

export type TransferSingleEventFilter = TypedEventFilter<TransferSingleEvent>;

export interface URIEventObject {
  value: string;
  id: BigNumber;
}
export type URIEvent = TypedEvent<[string, BigNumber], URIEventObject>;

export type URIEventFilter = TypedEventFilter<URIEvent>;

export interface VaultAccessGrantedEventObject {
  to: string;
  tokenId: BigNumber;
  permission: number;
}
export type VaultAccessGrantedEvent = TypedEvent<
  [string, BigNumber, number],
  VaultAccessGrantedEventObject
>;

export type VaultAccessGrantedEventFilter =
  TypedEventFilter<VaultAccessGrantedEvent>;

export interface VaultAccessRevokedEventObject {
  to: string;
  tokenId: BigNumber;
}
export type VaultAccessRevokedEvent = TypedEvent<
  [string, BigNumber],
  VaultAccessRevokedEventObject
>;

export type VaultAccessRevokedEventFilter =
  TypedEventFilter<VaultAccessRevokedEvent>;

export interface VaultCreatedEventObject {
  tokenId: BigNumber;
  owner: string;
  name: string;
  description: string;
  schemaCID: string;
}
export type VaultCreatedEvent = TypedEvent<
  [BigNumber, string, string, string, string],
  VaultCreatedEventObject
>;

export type VaultCreatedEventFilter = TypedEventFilter<VaultCreatedEvent>;

export interface VaultTransferredEventObject {
  tokenId: BigNumber;
  from: string;
  to: string;
}
export type VaultTransferredEvent = TypedEvent<
  [BigNumber, string, string],
  VaultTransferredEventObject
>;

export type VaultTransferredEventFilter =
  TypedEventFilter<VaultTransferredEvent>;

export interface Vault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<[string]>;

    PERMISSION_NONE(overrides?: CallOverrides): Promise<[number]>;

    PERMISSION_READ(overrides?: CallOverrides): Promise<[number]>;

    PERMISSION_WRITE(overrides?: CallOverrides): Promise<[number]>;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    createVault(
      tokenId: BigNumberish,
      name: string,
      description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    getCurrentSchema(overrides?: CallOverrides): Promise<[string]>;

    getNonce(owner: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getPermission(
      tokenId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getSchema(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getVaultOwner(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getVaultSchemaIndex(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    grantAccess(
      to: string,
      tokenId: BigNumberish,
      permission: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    grantAccessWithSignature(
      to: string,
      tokenId: BigNumberish,
      permission: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isApprovedForAll(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    lastSchemaIndex(overrides?: CallOverrides): Promise<[BigNumber]>;

    nonces(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    permissions(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    revokeAccess(
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    safeBatchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    safeTransferFrom(
      from: string,
      to: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    schemaCIDs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setSchema(
      schemaCID: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setURI(
      newuri: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    storeContentBatch(
      tokenId: BigNumberish,
      encryptedCIDs: BytesLike[],
      areCIDsEncrypted: boolean,
      metadatas: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    storeContentBatchWithSignature(
      tokenId: BigNumberish,
      encryptedCIDs: BytesLike[],
      areCIDsEncrypted: boolean,
      metadatas: BytesLike[],
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    storeContentWithMetadata(
      tokenId: BigNumberish,
      encryptedCID: BytesLike,
      isCIDEncrypted: boolean,
      metadata: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    storeContentWithMetadataSigned(
      tokenId: BigNumberish,
      encryptedCID: BytesLike,
      isCIDEncrypted: boolean,
      metadata: BytesLike,
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferVaultOwnership(
      tokenId: BigNumberish,
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    upgradePermission(
      tokenId: BigNumberish,
      user: string,
      newPermission: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    uri(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    vaultExists(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    vaults(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { owner: string; currentSchemaIndex: BigNumber }
    >;
  };

  DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

  PERMISSION_NONE(overrides?: CallOverrides): Promise<number>;

  PERMISSION_READ(overrides?: CallOverrides): Promise<number>;

  PERMISSION_WRITE(overrides?: CallOverrides): Promise<number>;

  balanceOf(
    account: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balanceOfBatch(
    accounts: string[],
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  createVault(
    tokenId: BigNumberish,
    name: string,
    description: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  eip712Domain(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber, string, string, BigNumber[]] & {
      fields: string;
      name: string;
      version: string;
      chainId: BigNumber;
      verifyingContract: string;
      salt: string;
      extensions: BigNumber[];
    }
  >;

  getCurrentSchema(overrides?: CallOverrides): Promise<string>;

  getNonce(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  getPermission(
    tokenId: BigNumberish,
    user: string,
    overrides?: CallOverrides
  ): Promise<number>;

  getSchema(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getVaultOwner(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getVaultSchemaIndex(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grantAccess(
    to: string,
    tokenId: BigNumberish,
    permission: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  grantAccessWithSignature(
    to: string,
    tokenId: BigNumberish,
    permission: BigNumberish,
    deadline: BigNumberish,
    signature: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isApprovedForAll(
    account: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lastSchemaIndex(overrides?: CallOverrides): Promise<BigNumber>;

  nonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  permissions(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<number>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  revokeAccess(
    tokenId: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  safeBatchTransferFrom(
    from: string,
    to: string,
    ids: BigNumberish[],
    values: BigNumberish[],
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  safeTransferFrom(
    from: string,
    to: string,
    id: BigNumberish,
    value: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  schemaCIDs(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  setApprovalForAll(
    operator: string,
    approved: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setSchema(
    schemaCID: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setURI(
    newuri: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  storeContentBatch(
    tokenId: BigNumberish,
    encryptedCIDs: BytesLike[],
    areCIDsEncrypted: boolean,
    metadatas: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  storeContentBatchWithSignature(
    tokenId: BigNumberish,
    encryptedCIDs: BytesLike[],
    areCIDsEncrypted: boolean,
    metadatas: BytesLike[],
    deadline: BigNumberish,
    signature: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  storeContentWithMetadata(
    tokenId: BigNumberish,
    encryptedCID: BytesLike,
    isCIDEncrypted: boolean,
    metadata: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  storeContentWithMetadataSigned(
    tokenId: BigNumberish,
    encryptedCID: BytesLike,
    isCIDEncrypted: boolean,
    metadata: BytesLike,
    deadline: BigNumberish,
    signature: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferVaultOwnership(
    tokenId: BigNumberish,
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  upgradePermission(
    tokenId: BigNumberish,
    user: string,
    newPermission: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  uri(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  vaultExists(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  vaults(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber] & { owner: string; currentSchemaIndex: BigNumber }
  >;

  callStatic: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

    PERMISSION_NONE(overrides?: CallOverrides): Promise<number>;

    PERMISSION_READ(overrides?: CallOverrides): Promise<number>;

    PERMISSION_WRITE(overrides?: CallOverrides): Promise<number>;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    createVault(
      tokenId: BigNumberish,
      name: string,
      description: string,
      overrides?: CallOverrides
    ): Promise<void>;

    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    getCurrentSchema(overrides?: CallOverrides): Promise<string>;

    getNonce(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    getPermission(
      tokenId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getSchema(index: BigNumberish, overrides?: CallOverrides): Promise<string>;

    getVaultOwner(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getVaultSchemaIndex(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantAccess(
      to: string,
      tokenId: BigNumberish,
      permission: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    grantAccessWithSignature(
      to: string,
      tokenId: BigNumberish,
      permission: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    isApprovedForAll(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lastSchemaIndex(overrides?: CallOverrides): Promise<BigNumber>;

    nonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    permissions(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<number>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    revokeAccess(
      tokenId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    safeBatchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    safeTransferFrom(
      from: string,
      to: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    schemaCIDs(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setSchema(schemaCID: string, overrides?: CallOverrides): Promise<void>;

    setURI(newuri: string, overrides?: CallOverrides): Promise<void>;

    storeContentBatch(
      tokenId: BigNumberish,
      encryptedCIDs: BytesLike[],
      areCIDsEncrypted: boolean,
      metadatas: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    storeContentBatchWithSignature(
      tokenId: BigNumberish,
      encryptedCIDs: BytesLike[],
      areCIDsEncrypted: boolean,
      metadatas: BytesLike[],
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    storeContentWithMetadata(
      tokenId: BigNumberish,
      encryptedCID: BytesLike,
      isCIDEncrypted: boolean,
      metadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    storeContentWithMetadataSigned(
      tokenId: BigNumberish,
      encryptedCID: BytesLike,
      isCIDEncrypted: boolean,
      metadata: BytesLike,
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferVaultOwnership(
      tokenId: BigNumberish,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradePermission(
      tokenId: BigNumberish,
      user: string,
      newPermission: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    uri(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    vaultExists(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    vaults(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { owner: string; currentSchemaIndex: BigNumber }
    >;
  };

  filters: {
    "ApprovalForAll(address,address,bool)"(
      account?: string | null,
      operator?: string | null,
      approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      account?: string | null,
      operator?: string | null,
      approved?: null
    ): ApprovalForAllEventFilter;

    "ContentStoredWithMetadata(address,uint256,bytes,bool,bytes,bool)"(
      sender?: string | null,
      tokenId?: BigNumberish | null,
      encryptedCID?: null,
      isCIDEncrypted?: null,
      metadata?: null,
      isMetadataSigned?: null
    ): ContentStoredWithMetadataEventFilter;
    ContentStoredWithMetadata(
      sender?: string | null,
      tokenId?: BigNumberish | null,
      encryptedCID?: null,
      isCIDEncrypted?: null,
      metadata?: null,
      isMetadataSigned?: null
    ): ContentStoredWithMetadataEventFilter;

    "EIP712DomainChanged()"(): EIP712DomainChangedEventFilter;
    EIP712DomainChanged(): EIP712DomainChangedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "PermissionUpgraded(address,uint256,uint8)"(
      user?: string | null,
      tokenId?: BigNumberish | null,
      newPermission?: null
    ): PermissionUpgradedEventFilter;
    PermissionUpgraded(
      user?: string | null,
      tokenId?: BigNumberish | null,
      newPermission?: null
    ): PermissionUpgradedEventFilter;

    "SchemaSet(uint256,string)"(
      index?: BigNumberish | null,
      schemaCID?: null
    ): SchemaSetEventFilter;
    SchemaSet(
      index?: BigNumberish | null,
      schemaCID?: null
    ): SchemaSetEventFilter;

    "TransferBatch(address,address,address,uint256[],uint256[])"(
      operator?: string | null,
      from?: string | null,
      to?: string | null,
      ids?: null,
      values?: null
    ): TransferBatchEventFilter;
    TransferBatch(
      operator?: string | null,
      from?: string | null,
      to?: string | null,
      ids?: null,
      values?: null
    ): TransferBatchEventFilter;

    "TransferSingle(address,address,address,uint256,uint256)"(
      operator?: string | null,
      from?: string | null,
      to?: string | null,
      id?: null,
      value?: null
    ): TransferSingleEventFilter;
    TransferSingle(
      operator?: string | null,
      from?: string | null,
      to?: string | null,
      id?: null,
      value?: null
    ): TransferSingleEventFilter;

    "URI(string,uint256)"(
      value?: null,
      id?: BigNumberish | null
    ): URIEventFilter;
    URI(value?: null, id?: BigNumberish | null): URIEventFilter;

    "VaultAccessGranted(address,uint256,uint8)"(
      to?: string | null,
      tokenId?: BigNumberish | null,
      permission?: null
    ): VaultAccessGrantedEventFilter;
    VaultAccessGranted(
      to?: string | null,
      tokenId?: BigNumberish | null,
      permission?: null
    ): VaultAccessGrantedEventFilter;

    "VaultAccessRevoked(address,uint256)"(
      to?: string | null,
      tokenId?: BigNumberish | null
    ): VaultAccessRevokedEventFilter;
    VaultAccessRevoked(
      to?: string | null,
      tokenId?: BigNumberish | null
    ): VaultAccessRevokedEventFilter;

    "VaultCreated(uint256,address,string,string,string)"(
      tokenId?: BigNumberish | null,
      owner?: string | null,
      name?: null,
      description?: null,
      schemaCID?: null
    ): VaultCreatedEventFilter;
    VaultCreated(
      tokenId?: BigNumberish | null,
      owner?: string | null,
      name?: null,
      description?: null,
      schemaCID?: null
    ): VaultCreatedEventFilter;

    "VaultTransferred(uint256,address,address)"(
      tokenId?: BigNumberish | null,
      from?: string | null,
      to?: string | null
    ): VaultTransferredEventFilter;
    VaultTransferred(
      tokenId?: BigNumberish | null,
      from?: string | null,
      to?: string | null
    ): VaultTransferredEventFilter;
  };

  estimateGas: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<BigNumber>;

    PERMISSION_NONE(overrides?: CallOverrides): Promise<BigNumber>;

    PERMISSION_READ(overrides?: CallOverrides): Promise<BigNumber>;

    PERMISSION_WRITE(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createVault(
      tokenId: BigNumberish,
      name: string,
      description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    eip712Domain(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentSchema(overrides?: CallOverrides): Promise<BigNumber>;

    getNonce(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    getPermission(
      tokenId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSchema(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultOwner(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultSchemaIndex(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantAccess(
      to: string,
      tokenId: BigNumberish,
      permission: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    grantAccessWithSignature(
      to: string,
      tokenId: BigNumberish,
      permission: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    isApprovedForAll(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastSchemaIndex(overrides?: CallOverrides): Promise<BigNumber>;

    nonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    permissions(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    revokeAccess(
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    safeBatchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    safeTransferFrom(
      from: string,
      to: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    schemaCIDs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setSchema(
      schemaCID: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setURI(
      newuri: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    storeContentBatch(
      tokenId: BigNumberish,
      encryptedCIDs: BytesLike[],
      areCIDsEncrypted: boolean,
      metadatas: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    storeContentBatchWithSignature(
      tokenId: BigNumberish,
      encryptedCIDs: BytesLike[],
      areCIDsEncrypted: boolean,
      metadatas: BytesLike[],
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    storeContentWithMetadata(
      tokenId: BigNumberish,
      encryptedCID: BytesLike,
      isCIDEncrypted: boolean,
      metadata: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    storeContentWithMetadataSigned(
      tokenId: BigNumberish,
      encryptedCID: BytesLike,
      isCIDEncrypted: boolean,
      metadata: BytesLike,
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferVaultOwnership(
      tokenId: BigNumberish,
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    upgradePermission(
      tokenId: BigNumberish,
      user: string,
      newPermission: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    uri(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    vaultExists(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vaults(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PERMISSION_NONE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PERMISSION_READ(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PERMISSION_WRITE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createVault(
      tokenId: BigNumberish,
      name: string,
      description: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    eip712Domain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrentSchema(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getNonce(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermission(
      tokenId: BigNumberish,
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSchema(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVaultOwner(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVaultSchemaIndex(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantAccess(
      to: string,
      tokenId: BigNumberish,
      permission: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    grantAccessWithSignature(
      to: string,
      tokenId: BigNumberish,
      permission: BigNumberish,
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      account: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastSchemaIndex(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nonces(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    permissions(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    revokeAccess(
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    safeBatchTransferFrom(
      from: string,
      to: string,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    safeTransferFrom(
      from: string,
      to: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    schemaCIDs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setSchema(
      schemaCID: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setURI(
      newuri: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    storeContentBatch(
      tokenId: BigNumberish,
      encryptedCIDs: BytesLike[],
      areCIDsEncrypted: boolean,
      metadatas: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    storeContentBatchWithSignature(
      tokenId: BigNumberish,
      encryptedCIDs: BytesLike[],
      areCIDsEncrypted: boolean,
      metadatas: BytesLike[],
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    storeContentWithMetadata(
      tokenId: BigNumberish,
      encryptedCID: BytesLike,
      isCIDEncrypted: boolean,
      metadata: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    storeContentWithMetadataSigned(
      tokenId: BigNumberish,
      encryptedCID: BytesLike,
      isCIDEncrypted: boolean,
      metadata: BytesLike,
      deadline: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferVaultOwnership(
      tokenId: BigNumberish,
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    upgradePermission(
      tokenId: BigNumberish,
      user: string,
      newPermission: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    uri(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vaultExists(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vaults(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
